/*
 * Processes related to genome and annotations
 */

process BUILD_STAR {
  conda 'envs/star.yml'
  label 'maxCPU'

  input:
    tuple path(genomeFasta), path(genomeGtf)
  output:
    path("STAR_REF")
  script:
    """
STAR --runThreadN ${task.cpus} \
--runMode genomeGenerate \
--limitGenomeGenerateRAM 35000000000 \
--genomeSAindexNbases 14 \
--genomeDir STAR_REF \
--genomeFastaFiles ${ genomeFasta } \
--sjdbGTFfile ${ genomeGtf } \
--sjdbOverhang 149
    """

}

/*
 * Aligned reads to both the genome and transciptome generated by STAR
 */


process ALIGN_STAR {
  conda 'envs/star.yml'
  label 'maxCPU'

  input:
    tuple val(sampleID), path(forward_read), path(reverse_read), path(STAR_INDEX_DIR)
  output:
    tuple val(sampleID), \
          path("${ sampleID }Aligned.sortedByCoord.out.bam"), emit: genomeMapping
    tuple val(sampleID), \
          path("${ sampleID }Aligned.toTranscriptome.out.bam"), emit: transcriptomeMapping
  script:
    """
    STAR --twopassMode Basic \
    --limitBAMsortRAM 65000000000 \
    --outFilterType BySJout \
    --outSAMunmapped Within \
    --genomeDir ${ STAR_INDEX_DIR } \
    --outSAMattributes NH HI AS NM MD MC \
    --outFilterMismatchNoverReadLmax 0.04 \
    --outFilterMismatchNmax 999 \
    --outFilterMultimapNmax 20 \
    --alignIntronMin 20 \
    --alignSJoverhangMin 8 \
    --alignMatesGapMax 1000000 \
    --alignIntronMax 1000000 \
    --alignSJDBoverhangMin 1 \
    --sjdbScore 1 \
    --outSAMtype BAM SortedByCoordinate \
    --runThreadN ${ task.cpus } \
    --readFilesCommand zcat \
    --quantMode TranscriptomeSAM \
    --outFileNamePrefix ${ sampleID } \
    --readFilesIn ${ forward_read } ${ reverse_read }
    """

}

process BUILD_RSEM {
  conda 'envs/rsem.yml'

  input:
    tuple path(genomeFasta), path(genomeGtf)
  output:
    path("RSEM_REF*")
  script:
    """
rsem-prepare-reference --gtf $genomeGtf $genomeFasta RSEM_REF
    """

}
